version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-test
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    network_mode: host
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181